const assert=require('node:assert/strict');
const {qualification,referenceScopeForPickup}=require('./market-reference-authority');
const plan={minimumIndependentFamilies:2,maxObservationAgeDays:90};
const now=Date.parse('2026-10-01T12:00:00Z');
const cell={targetTotalCents:1800,evidenceFamilies:['government-trips','independent-audit'],latestObservedAt:'2026-10-01T11:00:00Z'};
const promoted={asOf:'2026-10-01T11:30:00Z',promotion:{status:'promoted',snapshotAsOf:'2026-10-01T11:30:00Z',holdoutPassed:true,economicsPassed:true,routerPassed:true},cells:{x:cell}};
assert.equal(qualification(null,plan).ok,false);
assert.equal(qualification({asOf:'2026-10-01T11:30:00Z',promotion:{status:'candidate'},cells:{}},plan).ok,false);
assert.equal(qualification({...promoted,promotion:{...promoted.promotion,holdoutPassed:false}},plan).ok,false);
assert.equal(qualification(promoted,plan).ok,true);
assert.equal(qualification(promoted,plan,cell,now).ok,true);
assert.equal(qualification(promoted,plan,{...cell,evidenceFamilies:['government-trips']},now).ok,false);
assert.equal(qualification(promoted,plan,{...cell,latestObservedAt:'2026-01-01T00:00:00Z'},now).ok,false);
assert.equal(referenceScopeForPickup({lat:25.7959,lng:-80.287}),'fl-miami-dade');
assert.equal(referenceScopeForPickup({lat:26.0742,lng:-80.1506}),'fl-broward');
assert.equal(referenceScopeForPickup({lat:26.6832,lng:-80.0956}),'fl-palm-beach');
assert.equal(referenceScopeForPickup({lat:41.8781,lng:-87.6298}),null);
console.log('market-reference runtime authority tests passed');
