const fs = require('fs');
const assert = require('assert');
const firebase = fs.readFileSync('src/firebase.ts','utf8');
const app = JSON.parse(fs.readFileSync('app.json','utf8'));
assert.equal(app.expo.ios.infoPlist.CFBundleDisplayName, 'American');
assert.match(firebase, /projectId: 'american-rider-35688'/);
assert.match(firebase, /if \(!getRNPersistence\) \{/);
assert.match(firebase, /throw new Error\('firebase/native-persistence-unavailable/);
assert.match(firebase, /code === 'auth\/already-initialized'/);
assert.doesNotMatch(firebase, /getRNPersistence/);
console.log('native auth bootstrap invariants: PASS');
