const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const p = fs.readFileSync(path.join(__dirname,'payments.js'),'utf8');
assert.equal(/transfer_data\s*:/.test(p), false, 'Travel payment code must not create destination charges');
assert.equal(/application_fee_amount\s*:/.test(p), false, 'Travel payment code must not split funds at charge time');
assert.ok(p.includes('stripe.transfers.create'), 'Operator settlement must use explicit transfer');
assert.ok(p.includes('source_transaction: chargeId'), 'settlement transfer must be tied to the Travel charge');
assert.ok(p.includes('idempotencyKey: `ar_customer_${accountUid}`'), 'Stripe Customer creation is idempotent per immutable Firebase uid');
assert.ok(p.includes("collection('stripe_customers').doc(accountUid)"), 'Firebase uid has a durable server-owned Stripe Customer mapping');
assert.ok(p.includes("stripe.customers.retrieve(String(owned.data().customerId))"), 'mapped Customer is retrieved directly rather than rediscovered by search');
assert.ok(p.includes("Stripe Customer ownership mismatch"), 'Customer metadata mismatch fails closed');
assert.ok(p.includes("if (!customer || customer.deleted) throw new Error('Authoritative Stripe Customer is unavailable')"), 'deleted mapped Customer fails closed rather than creating a replacement');
const mappedBranch=p.slice(p.indexOf('if (ownerRef)'), p.indexOf('// Legacy adoption only'));
assert.ok(!mappedBranch.includes('customers.create'), 'mapped Customer failure path cannot manufacture a replacement Customer');
assert.ok(p.includes("Multiple Stripe Customers exist for this account"), 'ambiguous legacy Customer ownership fails closed rather than silently adopting one');
assert.ok(p.includes('await ownerRef.create'), 'first-use mapping is create-only so concurrent requests cannot overwrite ownership');
assert.ok(p.includes("if (!db) throw new Error('Stripe Customer ownership registry is unavailable')"), 'Customer provisioning never runs without its durable ownership registry');
assert.ok(p.includes("code === '6' || code === 'already-exists' || code === 'already_exists'"), 'only a genuine Firestore create conflict enters concurrent-winner reconciliation');
assert.ok(p.includes('if (!alreadyExists) throw e'), 'registry permission/network/quota failures propagate instead of masquerading as ownership conflicts');
const server = fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
assert.ok(server.includes("require('./runtime-mode')"), 'HTTP readiness uses shared runtime-mode authority');
assert.ok(p.includes('inspectStripeCustomerOwnership'), 'payment layer exposes read-only duplicate-Customer inventory');
assert.ok(p.includes('financialIdentityAuthorization'), 'Customer-dependent money activity has a server-owned reconciliation authorization generation');
assert.ok((p.match(/await assertFinancialIdentityAuthorization\(uid, financialAuth\.generation\)/g)||[]).length >= 2, 'authorization generation is rechecked at immediate and scheduled PaymentIntent creation boundaries');
assert.ok((p.match(/financialIdentityGeneration: String\(financialAuth\.generation\)/g)||[]).length >= 2, 'immediate and scheduled Stripe records retain the authorizing financial identity generation');
assert.ok(p.includes('paymentIntentsHasMore'), 'reconciliation inventory discloses when Stripe history is paginated rather than pretending completeness');
const ops = fs.readFileSync(path.join(__dirname,'ops.js'),'utf8');
assert.ok(ops.includes("app.get('/ops/stripe-customers'"), 'named Operations has an authenticated reconciliation evidence endpoint');
assert.ok(ops.includes("action: 'stripe_customer_reconciliation_inspected'"), 'financial identity inspection is audit logged');
assert.ok(ops.includes('mutationPerformed: false'), 'reconciliation endpoint is explicitly non-mutating');
assert.ok(ops.includes("app.post('/ops/stripe-customers/hold'"), 'named Operations can place a financial identity hold before reconciliation');
assert.ok(ops.includes("action:'financial_identity_hold_placed', generation"), 'financial identity hold placement and generation are audit logged');
assert.ok(ops.includes('const generation = Math.max(0, Number(current.data()?.generation) || 0) + 1'), 'placing a hold advances the monotonic financial identity generation');
assert.ok(!ops.includes("app.post('/ops/stripe-customers/release'"), 'no unsafe manual release exists before a complete reconciliation protocol');
console.log('✓ one money architecture: charge platform, transfer on completed Travel');
