const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const p = fs.readFileSync(path.join(__dirname,'payments.js'),'utf8');
assert.equal(/transfer_data\s*:/.test(p), false, 'Travel payment code must not create destination charges');
assert.equal(/application_fee_amount\s*:/.test(p), false, 'Travel payment code must not split funds at charge time');
assert.ok(p.includes('stripe.transfers.create'), 'Operator settlement must use explicit transfer');
assert.ok(p.includes('source_transaction: chargeId'), 'settlement transfer must be tied to the Travel charge');
assert.ok(p.includes('idempotencyKey: `ar_customer_${accountUid}`'), 'Stripe Customer creation is idempotent per immutable Firebase uid');
assert.ok(p.includes("collection('stripe_customers').doc(accountUid)"), 'Firebase uid has a durable server-owned Stripe Customer mapping');
assert.ok(p.includes("stripe.customers.retrieve(String(owned.data().customerId))"), 'mapped Customer is retrieved directly rather than rediscovered by search');
assert.ok(p.includes("Stripe Customer ownership mismatch"), 'Customer metadata mismatch fails closed');
assert.ok(p.includes("Multiple Stripe Customers exist for this account"), 'ambiguous legacy Customer ownership fails closed rather than silently adopting one');
assert.ok(p.includes('await ownerRef.create'), 'first-use mapping is create-only so concurrent requests cannot overwrite ownership');
assert.ok(p.includes("if (!db) throw new Error('Stripe Customer ownership registry is unavailable')"), 'Customer provisioning never runs without its durable ownership registry');
assert.ok(p.includes("code === '6' || code === 'already-exists' || code === 'already_exists'"), 'only a genuine Firestore create conflict enters concurrent-winner reconciliation');
assert.ok(p.includes('if (!alreadyExists) throw e'), 'registry permission/network/quota failures propagate instead of masquerading as ownership conflicts');
const server = fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
assert.ok(server.includes("require('./runtime-mode')"), 'HTTP readiness uses shared runtime-mode authority');
console.log('✓ one money architecture: charge platform, transfer on completed Travel');
