const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {scheduledIdentity}=require('./scheduledidentity');
const input={uid:'traveler-A',atMs:Date.parse('2026-10-08T10:30:00Z'),pickup:{lat:25.777,lng:-80.19},destination:{lat:25.9,lng:-80.25},travelClass:'Standard',party:{mode:'self',travelerUid:'traveler-A'}};
const first=scheduledIdentity(input);
assert.match(first.id,/^scheduled_[a-f0-9]{40}$/);
assert.deepEqual(scheduledIdentity({...input,pickup:{lng:-80.19,lat:25.777}}),first);
assert.notEqual(scheduledIdentity({...input,uid:'traveler-B'}).id,first.id);
assert.notEqual(scheduledIdentity({...input,atMs:input.atMs+604800000}).id,first.id);
assert.notEqual(scheduledIdentity({...input,party:{mode:'teen',travelerUid:'teen-A',familyLinkId:'link-A'}}).id,first.id);
assert.notEqual(scheduledIdentity({...input,destination:{lat:25.93,lng:-80.25}}).id,first.id);
const source=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
const route=source.split("app.post('/travel/schedule',")[1].split('// --- Who can bring a lost item back.')[0];
assert.match(route,/const identity = scheduledIdentity\(/);
assert.match(route,/const prior = await reservation\.get\(\)/);
assert.ok(route.indexOf('const prior = await reservation.get()') < route.indexOf('const priced = await authoritativeFare('));
assert.match(route,/priced\.travelerPays !== clientAmount/);
assert.match(route,/consentCents: clientAmount, requestFingerprint: identity\.fingerprint/);
assert.match(route,/const previous=await tx\.get\(ref\)/);
assert.match(route,/previous\.exists\) return previous\.data\(\)/);
const mobile=fs.readFileSync(path.join(__dirname,'../src/backend/scheduled.ts'),'utf8');
assert.match(mobile,/costCents: Math\.round\(info\.cost \* 100\)/);
console.log('PASS deterministic scheduled identity, consent ceiling and duplicate-before-price authority');
