const assert=require('node:assert');
const fs=require('fs'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');
const R=[];const check=(l,c)=>R.push({l,ok:!!c});
check('clock work is guarded by Firestore lease',/acquireLease\('operations_sweep'/.test(src));
check('non-owner skips sweep',/if \(!lease\.acquired\) return/.test(src));
check('internal timer calls leased sweep',/setInterval\([\s\S]*runLeasedSweeps\(\)/.test(src));
check('external scheduler calls leased sweep',/async function runSweep[\s\S]*runLeasedSweeps\(\)/.test(src));
check('external scheduler requires configured token',/const want = readKey\('SCHEDULER_TOKEN'\)[\s\S]*if \(!want \|\| got !== want\)[\s\S]*status\(401\)/.test(src));
for(const r of R)console.log(`${r.ok?'PASS':'FAIL'}  ${r.l}`);
const bad=R.filter(r=>!r.ok);console.log(`\n${R.length-bad.length}/${R.length} passed`);assert.equal(bad.length,0);
