const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const read=(p)=>fs.readFileSync(path.join(__dirname,'..',p),'utf8');
const server=read('backend/server.js');
const scheduler=read('backend/scheduler.js');
const scheduled=read('src/backend/scheduled.ts');
const party=read('backend/travelparty.js');
const teenPickup=read('backend/teenpickup.js');
const pushSource=read('backend/push.js');

assert.ok(server.includes("app.post('/travel/schedule'"), 'scheduled route exists');
assert.ok(server.includes('pickupRegion.timezone'), 'scheduled epoch is interpreted in the pickup market timezone');
assert.ok(server.includes("code: 'scheduled_time_mismatch'"), 'server rejects a client epoch that disagrees with the displayed civil appointment');
assert.ok(server.includes('civilDate !== serverDate || civilTime !== serverTime'), 'device clock/timezone cannot silently redefine the appointment');
assert.ok(server.includes('const partyResult = await normalizeParty(b'), 'scheduled route normalizes party through authoritative Family-aware policy');
assert.ok(server.includes('party,'), 'scheduled record persists party');
assert.ok(scheduler.includes('party: r.party || null'), 'scheduler carries party into live Travel');
assert.ok(scheduler.includes("doc(`scheduled_${id}`)"), 'scheduled Travel identity is deterministic across crash/replay');
assert.ok(scheduler.includes('if (existingRide.exists)'), 'scheduler recovers an already-created Travel after a crash');
assert.ok(scheduler.includes('effectiveOperator = {'), 'replay preserves the Operator already committed to the Travel');
assert.ok(scheduler.includes("emitOnce('operatorAssigned'"), 'operator assignment has independent durable completion');
assert.ok(scheduler.includes("emitOnce('travelerAssigned'"), 'traveler assignment has independent durable completion');
assert.ok(scheduler.includes("emitOnce('teenPickupCode'"), 'Teen PIN delivery has independent durable completion');
assert.ok(scheduler.includes('provisionTeenPin'), 'replay can recover the existing Teen PIN before resuming missing effects');
assert.ok(teenPickup.includes("createCipheriv('aes-256-gcm'"), 'Teen PIN recovery material is authenticated-encrypted, not plaintext');
assert.ok(teenPickup.includes('TEEN_PIN_SEAL_KEY'), 'Teen PIN recovery requires server-held key material');
assert.ok(teenPickup.includes('TEEN_PIN_SEAL_KEY_PREVIOUS'), 'Teen PIN recovery survives controlled seal-key rotation');
assert.ok(teenPickup.includes("['current','previous']"), 'PIN unsealing supports the current/previous key rotation window');
assert.ok(teenPickup.includes('if(current?.sealedPin)'), 'Teen PIN provisioning recovers rather than rotates an existing code');
assert.ok(teenPickup.includes('credentialRetiredAt'), 'successful Teen PIN verification retires credential material');
assert.ok(teenPickup.includes('hash:_hash') && teenPickup.includes('sealedPin:_sealedPin'), 'verification removes both PIN hash and recoverable ciphertext');
assert.ok(scheduled.includes('civilDate?: string') && scheduled.includes('civilTime?: string'), 'client contract carries the displayed civil appointment for server validation');
assert.ok(scheduled.includes("party?: { mode: 'self' | 'other_adult'"), 'client scheduled contract supports another adult');
assert.ok(scheduled.includes("mode: 'self' | 'other_adult' | 'teen'"), 'client scheduled contract supports authorized Teen Travel');
assert.ok(party.includes('normalizeTeenParty'), 'server delegates scheduled Teen Travel to Family authorization');
assert.ok(scheduler.includes('out?.retryable'), 'transient push failure remains eligible for scheduler recovery');
assert.ok(scheduler.includes('dispatchEffects.${key}'), 'dispatch checkpoints update one nested effect instead of replacing siblings');
assert.ok(pushSource.includes('retryable: true'), 'push transport exceptions are retryable');
assert.ok(pushSource.includes("code === 'DeviceNotRegistered'"), 'invalid device token is terminal rather than endlessly retried');

console.log('✓ scheduled Travel preserves Booker/Traveler party semantics');
console.log('✓ scheduled Teen Travel uses Family authorization');
